require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const authRoutes = require('./routes/authRoutes');
const therapistRoutes = require('./routes/therapistRoutes');
const clientRoutes = require('./routes/clientRoutes');
const clientPortalRoutes = require('./routes/clientPortalRoutes');
const clientBookingRoutes = require('./routes/clientBookingRoutes');
const schedulingRoutes = require('./routes/schedulingRoutes');
const paymentRoutes = require('./routes/paymentRoutes');
const noteRoutes = require('./routes/noteRoutes');
const analyticsRoutes = require('./routes/analyticsRoutes');
const leadRoutes = require('./routes/leadRoutes');
const packageRoutes = require('./routes/packageRoutes');
const { notFound, errorHandler } = require('./middleware/errorHandler');

const app = express();
app.use(helmet());
app.use(cors({ origin: process.env.CLIENT_URL || 'unloxmajorproject-production.up.railway.app:5000/'||'https://api.razorpay.com' }));
app.use(express.json({ limit: '3mb', verify: (req, res, buffer) => {
	if (req.originalUrl === '/payments/webhook') req.rawBody = Buffer.from(buffer);
} }));
app.use(morgan('dev'));
app.get('/health', (req, res) => res.status(200).json({ status: 'ok', service: 'unfazed-api' }));
app.use('/auth', authRoutes);
app.use('/therapists', therapistRoutes);
app.use('/clients', clientPortalRoutes);
app.use('/client-booking', clientBookingRoutes);
app.use('/clients', clientRoutes);
app.use('/scheduling', schedulingRoutes);
app.use('/payments', paymentRoutes);
app.use('/notes', noteRoutes);
app.use('/analytics', analyticsRoutes);
app.use('/leads', leadRoutes);
app.use('/packages', packageRoutes);
app.use(notFound);
app.use(errorHandler);
module.exports = app;

